version: 2.1

orbs:
    python: circleci/python@2.1.1

jobs:
  build-and-test-triangle:
    docker:
      - image: cimg/python:3.12.6
    steps:
      - checkout
      - run:
          name: List files
          command: ls -R
      - run:
          command:  |
            pip install pytest
            pytest --junitxml=test-results/junit.xml Triangle567/TestTriangle.py
      - store_test_results:
          path: test-results
  
  build-and-test-githubAPI:
    docker:
      - image: cimg/python:3.12.6
    steps:
      - checkout
      - run:
          name: List files
          command: ls -R
      - run:
          command:  |
            pip install pytest
            pip install requests
            pytest --junitxml=test-results/junit.xml GitHubAPI567/TestGithubAPI.py
      - store_test_results:
          path: test-results

workflows:
  testing_triangles:
    jobs:
      - build-and-test-triangle
      - build-and-test-githubAPI